
## Where the samples will be written
save_data: pos/run/example
## Where the vocab(s) will be written
src_vocab: pos/run/example.vocab.src
tgt_vocab: pos/run/example.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: true

# Corpus opts:
data:
    corpus_1:
        path_src: short/train.fr
        path_tgt: short/train.en
        transforms: [inferfeats, filtertoolong]
        weight: 1
    valid:
        path_src: short/val.fr
        path_tgt: short/val.en
        transforms: [inferfeats]


# Vocabulary files that were just created
#src_vocab: baseline/run/example.vocab.src
#tgt_vocab: baseline/run/example.vocab.tgt



# Transform options
reversible_tokenization: "joiner"

# Features options
n_src_feats: 1
src_feats_defaults: "0"
feat_merge: "concat"
####################################################################################################################
# General opts
save_model: pos/run/model/
save_checkpoint_steps: 5000
valid_steps: 5000
train_steps: 50000 #50000

# Batching
bucket_size: 262144
world_size: 1
gpu_ranks: [0]
num_workers: 2
batch_type: "tokens"
batch_size: 4096
valid_batch_size: 2048
accum_count: [4]
accum_steps: [0]

# Optimization
model_dtype: "fp16"
optim: "adam"
learning_rate: 2
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 6
dec_layers: 6
heads: 8
hidden_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]
